spring:
  ai:
    openai:
      # base-url: http://127.0.0.1:1234
      api-key: sk-
      chat:
        options:
          model: gpt-4.1-nano
          temperature: 0.2
          max-tokens: 1024
      embedding:
        options:
          model: text-embedding-3-small
          dim: 1536
          batchSize: 700

logging:
  level:
    org.flywaydb: DEBUG
    org.springframework.web.reactive.function.client: DEBUG
    org.springframework.ai: DEBUG
    org.springframework.jdbc.core: DEBUG